description = "Computer Science researcher focused on Machine Learning, Deep Learning, NLP, Bangla NLP, and Large Language Models."
fullName = "MD. MAMUN UR RASHID HRIDOY"
email = "rashid15-5273@diu.edu.bd"
location = "Mohammadpur, Dhaka"
github = "https://github.com/mdmamunurrashidhridoy"